### ISSUE TITLE
Wrong version number reported

### ISSUE THREAD

**Issue by agowa338** [vim/vim-win32-installer#215] opened 2021-06-06 11:05 UTC
Currently, the setup reports the wrong version number.
After installing 8.2.2929 it only reports itself as 8.2
This causes errors with the upgrade detection of package managers like Winget. These then attempt to upgrade the package on every invocation...

**Comment by k-takata** [comment] 2021-06-06 11:51
How did you check the version?

**Comment by agowa338** [comment] 2021-06-09 09:39
It's checked using the registry key:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Vim 8.2\DisplayVersion`
This is what every package manager and deployment tool uses.

**Comment by ItzLevvie** [comment] 2021-07-14 18:00
I can confirm that it's still an issue today.

Downloaded from Windows Package Manager (it downloads the `8.2.3159` version):
![image](https://user-images.githubusercontent.com/11600822/125670051-caa16d32-b017-4149-a690-7a767b8ac789.png)

Control Panel shows that I've `8.2` installed rather than `8.2.3159` - this results in `winget upgrade `vim.vim` upgrading the application unlimited amount of times which results in an upgrade loop because of `8.2.3159` is higher than `8.2`:
![image](https://user-images.githubusercontent.com/11600822/125670195-07cdf048-26ae-4fe1-aabd-471c41d0fe2d.png)

**Comment by chrisbra** [comment] 2021-07-14 20:04
So I suppose this should be better:
![image](https://user-images.githubusercontent.com/244927/125685473-c57a78c7-8481-47cb-ba91-fa7c4074b900.png)
![image](https://user-images.githubusercontent.com/244927/125685549-180f9110-e100-4814-b417-7f4862b657ee.png)


Here is a patch:
https://github.com/chrisbra/vim-win32-installer/blob/master/patch/version.patch

Ping @brammool How about that patch?

**Comment by brammool** [comment] 2021-07-15 12:15
included as 8.2.3164.  Please close the issue if it works now.

**Comment by chrisbra** [comment] 2021-07-15 12:26
let me close it now. It should be there then with the next appveyor run (tomorrow).

**Closed by chrisbra** 2021-07-15 12:26 UTC
