### ISSUE TITLE
the cursor stays top-left

### ISSUE THREAD

**Issue by OsmondGao** [vim/vim-win32-installer#222] opened 2021-07-14 08:46 UTC
I installed vim(gvim_8.2.3159_x64) on WinServer.

Then I use telnet clinet(Microsoft's) to login WinServer.

After login success,I type vim to edit some text file(command line mode),but the cursor stays the top-left and never move whatever I pressed the keyboard(including i or :).

Anyone know how to resolve it?

**Comment by k-takata** [comment] 2021-07-14 09:16
Duplicate of #218

**Closed by k-takata** 2021-07-14 09:16 UTC
